//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinRH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talento()
        {
            this.Conhecimento = new HashSet<Conhecimento>();
        }
    
        public int id_Talento { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Banco { get; set; }
        public string Agencia { get; set; }
        public string TipoDeConta { get; set; }
        public string NumeroDaConta { get; set; }
        public string OBS_Conhecimentos { get; set; }
        public string LinkCRUD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conhecimento> Conhecimento { get; set; }
    }
}
